### ISSUE TITLE
Dash 3.4.0 not compatible with Dash extensions enrich

### ISSUE THREAD

**Issue by marcstern14** [thedirtyfew/dash-extensions#400]
In dash 3.4.0 the `_Wildcard` import has been changed to `Wildcard`, per [here](https://github.com/plotly/dash/issues/3580).

When upgrading to 3.4.0 it causes an import error that looks like the following.

```
  File "/app.py", line 3, in <module>
    from dash_extensions.enrich import DashProxy, Input, Serverside, dcc, html, page_container, ServersideOutputTransform, Output, State
  File "/usr/src/app/.venv/lib/python3.12/site-packages/dash_extensions/enrich.py", line 48, in <module>
    from dash.dependencies import DashDependency, _Wildcard  # lgtm [py/unused-import]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name '_Wildcard' from 'dash.dependencies' (/usr/src/app/.venv/lib/python3.12/site-packages/dash/dependencies.py)
cannot import name '_Wildcard' from 'dash.dependencies' (/usr/src/app/.venv/lib/python3.12/site-packages/dash/dependencies.py)
```

The import that needs to be changed is found here: https://github.com/emilhe/dash-extensions/blob/78d1de50d32f888e5f287cfedfa536fe314ab0b4/dash_extensions/enrich.py#L48

Given that dash extensions does not yet run on dash 3.4.0, I don't want to make a PR, but it does have a breaking downstream effect for the latest version of dash.

**Comment by araichev** [comment]
Ditto for Dash 4.0 (with the same ImportError).
